# Generated by Django 5.0.6 on 2024-06-23 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maceta',
            old_name='tamaño',
            new_name='tamanio',
        ),
    ]
